version: '3.9'
services:
  mysql-kc:
    image: mysql:8.0.27
    ports:
      - 3377:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: keycloak_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  mysql-service:
    image: mysql:8.0.27
    ports:
      - 3379:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: Quiz
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - Quiz-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak-w:
    image: quay.io/keycloak/keycloak:23.0.7
    command: start-dev
    ports:
      - 8081:8080
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN : admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:mysql://mysql-kc:3306/keycloak_db
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      KC_HOSTNAME: localhost
    depends_on:
      - mysql-kc
    networks:
      - keycloak-and-mysql-network



networks:
  keycloak-and-mysql-network:
  Quiz-and-mysql-network:

volumes:
  keycloak-and-mysql-volume:
  Quiz-and-mysql-volume:
